_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_mae
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 35
                - 41
                - 55
                - 106
            "2":
                - 1
                - 35
                - 41
                - 55
                - 106
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.13.9
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
dropout:
    value: 0.2
hidden_size:
    value: 8
input_size:
    value: 1
learning_rate:
    value: 1.6795782036410287e-05
num_layers:
    value: 2
pred_length:
    value: 96
